create table items
(
    id    integer generated by default as identity,
    price integer      not null,
    name  varchar(255) not null,
    primary key (id)
);

create table cart_item
(
    user_id  varchar(16) not null,
    item_id  integer     not null,
    quantity integer     not null,
    primary key (user_id, item_id)
);

create table orders
(
    id           integer generated by default as identity,
    user_id      varchar(16),
    discount     integer not null,
    order_status integer not null, -- 1 NEW, 2 DONE, 3 CANCEL
    order_date   date    not null,
    primary key (id)
);

create table order_item
(
    order_id integer not null,
    item_id  integer not null,
    quantity integer not null,
    price    integer not null,
    primary key (order_id, item_id)
);
