-- ==========================================
-- Categories (Internet service tiers)
-- ==========================================
create table categories
(
    id             integer generated by default as identity,
    name           varchar(50) not null,
    price_per_hour integer     not null,
    primary key (id)
);

-- ==========================================
-- Users
-- ==========================================
create table users
(
    id          integer generated by default as identity,
    username    varchar(50)  not null unique,
    full_name   varchar(255) not null,
    password    varchar(255) not null,
    balance     integer      not null default 0,
    category_id integer      not null,
    created_at  timestamp    not null default current_timestamp,
    primary key (id),
    foreign key (category_id) references categories (id)
);

-- ==========================================
-- User Balance Transactions
-- ==========================================
create table user_balance_transactions
(
    id          integer generated by default as identity,
    user_id     integer      not null,
    amount      integer      not null,
    type        integer      not null, -- 1=DEPOSIT, 2=ORDER_PAYMENT, 3=SESSION_PAYMENT
    description varchar(255),
    created_at  timestamp    not null default current_timestamp,
    primary key (id),
    foreign key (user_id) references users (id)
);

-- ==========================================
-- Sessions (Internet usage tracking)
-- ==========================================
create table sessions
(
    id             integer generated by default as identity,
    user_id        integer   not null,
    category_id    integer   not null,
    start_time     timestamp not null default current_timestamp,
    end_time       timestamp,
    price_per_hour integer   not null,
    status         integer   not null default 1, -- 1=ACTIVE, 2=EXPIRED, 3=CANCELLED
    primary key (id),
    foreign key (user_id) references users (id),
    foreign key (category_id) references categories (id)
);

-- ==========================================
-- Items (Food & Drink menu)
-- ==========================================
create table items
(
    id        integer generated by default as identity,
    name      varchar(255) not null,
    price     integer      not null,
    item_type integer      default 1, -- 1=FOOD, 2=DRINK
    primary key (id)
);

-- ==========================================
-- Cart
-- ==========================================
create table cart_item
(
    user_id  integer not null,
    item_id  integer not null,
    quantity integer not null,
    primary key (user_id, item_id),
    foreign key (user_id) references users (id),
    foreign key (item_id) references items (id)
);

-- ==========================================
-- Orders
-- ==========================================
create table orders
(
    id           integer generated by default as identity,
    user_id      integer not null,
    discount     integer not null default 0,
    order_status integer not null default 1, -- 1=NEW, 2=DONE, 3=CANCEL
    order_date   date    not null default current_date,
    total_amount integer,
    primary key (id),
    foreign key (user_id) references users (id)
);

-- ==========================================
-- Order Items
-- ==========================================
create table order_item
(
    order_id integer not null,
    item_id  integer not null,
    quantity integer not null,
    price    integer not null,
    primary key (order_id, item_id),
    foreign key (order_id) references orders (id),
    foreign key (item_id) references items (id)
);

