-- ===========================================================================
-- V1: Khởi tạo toàn bộ cấu trúc bảng cho Internet Shop Management Service
-- ===========================================================================

-- ==========================================
-- 1. categories — Gói cước internet
-- ==========================================
CREATE TABLE categories
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(50) NOT NULL,
    price_per_hour INTEGER     NOT NULL,
    PRIMARY KEY (id)
);

-- ==========================================
-- 2. users — Tài khoản người dùng
-- ==========================================
CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    full_name   VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    balance     INTEGER      NOT NULL DEFAULT 0,
    category_id INTEGER      NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories (id)
);

-- ==========================================
-- 3. user_balance_transactions — Lịch sử giao dịch số dư
-- ==========================================
CREATE TABLE user_balance_transactions
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id     INTEGER      NOT NULL,
    amount      INTEGER      NOT NULL,
    type        INTEGER      NOT NULL, -- 1=DEPOSIT, 2=ORDER_PAYMENT, 3=SESSION_PAYMENT
    description VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ==========================================
-- 4. sessions — Phiên sử dụng internet
-- ==========================================
CREATE TABLE sessions
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id        INTEGER   NOT NULL,
    category_id    INTEGER   NOT NULL,
    start_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time       TIMESTAMP,
    price_per_hour INTEGER   NOT NULL,
    status         INTEGER   NOT NULL DEFAULT 1, -- 1=ACTIVE, 2=EXPIRED, 3=CANCELLED
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (category_id) REFERENCES categories (id)
);

-- ==========================================
-- 5. items — Menu đồ ăn / thức uống
-- ==========================================
CREATE TABLE items
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255) NOT NULL,
    price     INTEGER      NOT NULL,
    item_type INTEGER      DEFAULT 1, -- 1=FOOD, 2=DRINK
    PRIMARY KEY (id)
);

-- ==========================================
-- 6. cart_item — Giỏ hàng
-- ==========================================
CREATE TABLE cart_item
(
    user_id  INTEGER NOT NULL,
    item_id  INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    PRIMARY KEY (user_id, item_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (item_id) REFERENCES items (id)
);

-- ==========================================
-- 7. orders — Đơn hàng
-- ==========================================
CREATE TABLE orders
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id      INTEGER NOT NULL,
    discount     INTEGER NOT NULL DEFAULT 0,
    order_status INTEGER NOT NULL DEFAULT 1, -- 1=NEW, 2=DONE, 3=CANCEL
    order_date   DATE    NOT NULL DEFAULT CURRENT_DATE,
    total_amount INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ==========================================
-- 8. order_item — Chi tiết đơn hàng
-- ==========================================
CREATE TABLE order_item
(
    order_id INTEGER NOT NULL,
    item_id  INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    price    INTEGER NOT NULL,
    PRIMARY KEY (order_id, item_id),
    FOREIGN KEY (order_id) REFERENCES orders (id),
    FOREIGN KEY (item_id) REFERENCES items (id)
);

